name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: save key
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > github.pub

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no -i "github.pub" ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} 'cd /var/www/html/test/triton && git pull origin main'
